[package]
name = "walrus_sql"
version = "0.0.1"
published-at = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet-v1.67.2" }

[addresses]
walrus_sql = "0x0"
